### ISSUE TITLE
Mac OSX & Ubuntu 16.10 compile errors - lots of errors

### ISSUE THREAD

**Issue by DonaldFoss** [rvagg/lmdb#18]
Using "yarn add level-lmdb".  Similar behavior using "npm install -s level-lmdb".

The attached log file is from Mac OSX 10.12.3 only. I can attach a log from Ubuntu also if needed.

All errors appear to be coming from nan.h and nobe_buffer.h.

module version tree:
└─┬ level-lmdb@0.17.0
  ├─┬ level-packager@0.17.0
  │  └─┬ levelup@0.17.0
  │         ├─┬ bops@0.0.7
  │        │   ├── base64-js@0.0.2
  │        │ └── to-utf8@0.0.1
  │        ├── concat-stream@0.1.1
  │        ├─┬ deferred-leveldown@0.0.1
  │       │   └── abstract-leveldown@0.10.2
  │        ├── errno@0.1.4
  │        ├── prr@0.0.0
  │        ├─┬ readable-stream@1.0.34
  │       │ ├── core-util-is@1.0.2
  │       │ ├── inherits@2.0.3
  │       │ ├── isarray@0.0.1
  │       │ └── string_decoder@0.10.31
  │       ├── semver@1.1.4
  │       └─┬ xtend@2.1.2
  │              └── object-keys@0.4.0
  └─┬ lmdb@0.1.3
         ├── bindings@1.1.1
        └── nan@0.3.2

[level-lmdb.log.txt](https://github.com/rvagg/lmdb/files/811415/level-lmdb.log.txt)

**Comment by DonaldFoss** [comment]
After changing dependency versions in lmdb/package.json to bindings@1.2.1 and nan@2.5.1, I get different compilation errors (Mac OSX 10.12.3 only).

  CC(target) Release/obj.target/liblmdb/deps/liblmdb-20130601/mdb.o
  CC(target) Release/obj.target/liblmdb/deps/liblmdb-20130601/midl.o
  LIBTOOL-STATIC Release/lmdb.a
  CXX(target) Release/obj.target/nlmdb/src/nlmdb.o
In file included from ../src/nlmdb.cc:5:
../src/nlmdb.h:145:34: error: use of undeclared identifier 'NanPersistentToLocal'
  if (!node::Buffer::HasInstance(NanPersistentToLocal(handle)->Get(NanSymbol("obj"))))
                                 ^
../src/nlmdb.h:145:68: error: use of undeclared identifier 'NanSymbol'
  if (!node::Buffer::HasInstance(NanPersistentToLocal(handle)->Get(NanSymbol("obj"))))
                                                                   ^
../src/nlmdb.h:147:3: error: use of undeclared identifier 'NanDispose'
  NanDispose(handle);
  ^
In file included from ../src/nlmdb.cc:6:
../src/database.h:48:34: error: too few arguments to function call, expected 1, have 0; did you mean 'Nan::New'?
    v8::Local<v8::Object> _obj = v8::Object::New();
                                 ^~
                                 Nan::New
/Users/donald/tmp/node_modules/lmdb/node_modules/nan/nan_new.h:259:25: note: 'Nan::New' declared here
    inline v8::Local<T> New(v8::Persistent<T, M> const& p);
                        ^
In file included from ../src/nlmdb.cc:6:
../src/database.h:49:15: error: use of undeclared identifier 'NanSymbol'
    _obj->Set(NanSymbol("obj"), obj);
              ^
../src/database.h:50:35: error: expected '(' for function-style cast or type construction
    NanAssignPersistent(v8::Object, handle, _obj);
                        ~~~~~~~~~~^
../src/nlmdb.cc:18:33: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Nan::NAN_METHOD_RETURN_TYPE
      (Nan::NAN_METHOD_ARGS_TYPE)' (aka 'void (const FunctionCallbackInfo<v8::Value> &)')
      v8::FunctionTemplate::New(NLMDB)->GetFunction();
                                ^~~~~
/Users/donald/.node-gyp/7.6.0/include/node/v8.h:5079:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
../src/nlmdb.cc:20:27: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(v8::String::NewSymbol("nlmdb"), nlmdb);
              ~~~~~~~~~~~~^
8 errors generated.
make: *** [Release/obj.target/nlmdb/src/nlmdb.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/donald/tmp/node_modules/lmdb
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
error Command failed with exit code 1.
